from fpdf import FPDF
import datetime

class EDAReport(FPDF):
    def header(self):
        self.set_fill_color(83, 74, 183)
        self.rect(0, 0, 210, 20, 'F')
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(255, 255, 255)
        self.cell(0, 20, "SmartEDA - Full Analysis Report", align="C",
                  new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Generated by SmartEDA | Page {self.page_no()}", align="C")

    def section_title(self, title):
        self.set_font("Helvetica", "B", 12)
        self.set_fill_color(238, 237, 254)
        self.set_text_color(60, 52, 137)
        self.cell(0, 9, title, fill=True, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        self.ln(2)

    def body_text(self, text):
        clean = str(text).encode("latin-1", errors="replace").decode("latin-1")
        self.set_font("Helvetica", size=10)
        self.multi_cell(0, 6, clean)
        self.ln(1)

    def metric_row(self, label, value):
        self.set_font("Helvetica", "B", 10)
        self.cell(70, 7, str(label) + ":", border=0)
        self.set_font("Helvetica", size=10)
        self.cell(0, 7, str(value), border=0, new_x="LMARGIN", new_y="NEXT")

def generate_pdf(overview, col_stats_df, outliers, suggestions,
                 quality_score, insights, top_corr, cleaning_log):
    pdf = EDAReport()
    pdf.add_page()

    # Date
    pdf.set_font("Helvetica", size=9)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 6, f"Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}",
             new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)

    # Overview
    pdf.section_title("1. Dataset Overview")
    pdf.metric_row("Total rows", overview['rows'])
    pdf.metric_row("Total columns", overview['columns'])
    pdf.metric_row("Missing values", f"{overview['missing_pct']}%")
    pdf.metric_row("Duplicate rows", overview['duplicate_rows'])
    pdf.metric_row("Numeric columns", overview['numeric_cols'])
    pdf.metric_row("Categorical columns", overview['categorical_cols'])
    pdf.metric_row("Data quality score", f"{quality_score}/100")
    pdf.ln(4)

    # Auto insights
    pdf.section_title("2. Auto Insights")
    for itype, text in insights:
        prefix = "[!] " if itype == "warning" else "[i] " if itype == "info" else "[OK] "
        pdf.body_text(prefix + text)
    pdf.ln(4)

    # Column stats
    pdf.section_title("3. Column Statistics")
    for _, row in col_stats_df.iterrows():
        line = f"{row['column']} ({row['dtype']}) - {row['missing']} missing ({row['missing_pct']}%), {row['unique']} unique"
        if row['mean'] is not None and str(row['mean']) != 'nan':
            line += f" | mean={row['mean']}, std={row['std']}, skew={row['skewness']}"
        pdf.body_text(line)
    pdf.ln(4)

    # Top correlations
    if top_corr:
        pdf.section_title("4. Top Correlations")
        for a, b, v in top_corr:
            strength = "Strong" if v > 0.7 else "Moderate"
            pdf.body_text(f"{strength} correlation between '{a}' and '{b}': {v}")
        pdf.ln(4)

    # Outliers
    pdf.section_title("5. Outlier Summary")
    total = sum(outliers.values())
    pdf.body_text(f"Total outliers detected: {total}")
    for col, count in outliers.items():
        if count > 0:
            pdf.body_text(f"  {col}: {count} outliers")
    pdf.ln(4)

    # ML suggestions
    pdf.section_title("6. ML Suggestions")
    for s in suggestions:
        pdf.body_text(f"* {s}")
    pdf.ln(4)

    # Cleaning log
    if cleaning_log:
        pdf.section_title("7. Cleaning Steps Applied")
        for step in cleaning_log:
            pdf.body_text(f"* {step}")

    return bytes(pdf.output())